### ISSUE TITLE
All day events are being displayed wrong

### ISSUE THREAD

**Issue by djmtype** [mmonkey/google_calendar_events#2]
If you choose to make your event an all-day event, the date of the event is being displayed 1 day before the actual event. 

For example, a March 9 all-day event is displaying as March 8.

**Comment by djmtype** [comment]
I thought maybe the offset wasn't matching, but my timezone ID looks to be correct.
`timeZoneId : 'America/New_York',`

**Comment by djmtype** [comment]
Does this need an timezone parameter?

**Comment by cjohara** [comment]
According to the google calendar API docs, it seems that they do provide an optional `timeZone` parameter on the [events list endpoint](https://developers.google.com/calendar/v3/reference/events/list). It should default to the calendar's default timezone, so if you are displaying the events in a different timezone than the calendar is set to, then I believe adding the timeZone parameter would fix any issues like this.

Update incoming.

**Comment by djmtype** [comment]
@cjohara It didn't seem to have any effect. I'm just using the default timezone set in my calendar which is -4 hours from GMT. Google's timezone name for this is `America/New_York`. What's happening regardless if I set a timezone or not, is that it seems to be applying -4 hours to all day events making them display a day prior. In words, all day events are starting at 8pm the day before. 

Without modifying any of your code, you can see for yourself. Just make an event all day by checking the all day input box. Let me know if you're getting the same result.

**Comment by cjohara** [comment]
As I dig in a bit more, I think I know what the issue is. I am going to be doing some more tests, but I think it actually has to do with how the date gets formatted on the plugin side. I don't believe that the timezone is taken into account when determining the start time.

**Comment by mmonkey** [comment]
@djmtype please take a look at the new v2.0.0 release.
